os: Visual Studio 2017

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - cmd: build.cmd /configure
  - cmd: echo /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" >> msbuild.rsp
  - cmd: build.cmd /release
  - cmd: .nuget\packages\coveralls.io\tools\coveralls.net.exe --opencover out\coverage.xml

# we run the tests ourselves in build.cmd for coverage
test: off

environment:
  COVERALLS_REPO_TOKEN:
    secure: l3O4lbgUscsMKm9M580fsx0rBDal/nTrtRTt3ZE6897ps9Q3USzEIwR254Z4CfKv

# build cache to preserve files/folders between builds
cache:
  - '%LocalAppData%\NuGet\Cache'
  - '%USERPROFILE%\.nuget\packages'

deploy:
  - provider: NuGet
    api_key:
      secure: 7MS5+XWaFchMXFqzgneQCqo9U0DlxiPXe/KWWUnbCBDEizVn06EjdQZkWu1gbNOJ
    artifact: Package
    on:
      # we only deploy to public NuGet gallery when tagging the repo
      appveyor_repo_tag: true

  - provider: GitHub
    auth_token:
      secure: xD5WjlS/UktBZ4bmN2DtjtoSkP8MxecLiIdn+aYGcPJxFsHuNqshj44VNwD657T8
    artifact: 'Package,Installer,Vsix,Json,Zip'
    draft: true
    force_update: true
    prerelease: false
    on:
      # we only deploy to GitHub release when tagging the repo
      appveyor_repo_tag: true

nuget:
  project_feed: true
  
artifacts:
  - path: out\*.nupkg
    name: Package
  - path: out\*.msi
    name: Installer
  - path: out\*.vsix
    name: Vsix
  - path: out\*.json
    name: Json
  - path: out\*.zip
    name: Zip
  - path: msbuild.log
    name: Log
